name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy App
        run: GIT_USER=${{ secrets.ACCESS_TOKEN }} GIT_USER_NAME=felipenasci GIT_USER_EMAIL=dfnascimento@live.com yarn deploy
