name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy App
        run: yarn deploy
